export const apiDataStructures = {
  apiRequestLog: {
    table: "api_request_logs",
    purpose: "Store every API request and response for audit/debugging.",
    fields: {
      id: "string primary key",
      method: "string",
      path: "string",
      statusCode: "number",
      durationMs: "number",
      origin: "string nullable",
      ip: "string nullable",
      userAgent: "string nullable",
      query: "json nullable",
      requestBody: "json nullable",
      responseBody: "json nullable",
      error: "string nullable",
      createdAt: "datetime",
    },
  },

  helperQuoteRequest: {
    table: "helper_quote_requests",
    purpose: "Store quote form input and generated helper offers from POST /api/helpers.",
    fields: {
      id: "string primary key",
      pickupZip: "string",
      dropoffZip: "string",
      helpers: "number nullable",
      rooms: "number nullable",
      volume: "number nullable",
      moveDate: "string nullable",
      request: "json",
      response: "json",
      resultCount: "number",
      selectedOfferId: "string nullable",
      aiStatus: "string nullable",
      aiText: "string nullable",
      aiModel: "string nullable",
      aiError: "string nullable",
      createdAt: "datetime",
      updatedAt: "datetime",
    },
  },

  routeRequest: {
    table: "route_requests",
    purpose: "Store route lookup input and returned route geometry from POST /api/maps/route.",
    fields: {
      id: "string primary key",
      pickupZip: "string nullable",
      dropoffZip: "string nullable",
      profile: "string",
      simplify: "boolean",
      inputCoordinates: "json nullable",
      routeCoordinates: "json nullable",
      error: "string nullable",
      createdAt: "datetime",
    },
  },

  aiRequestLog: {
    table: "ai_request_logs",
    purpose: "Store AI prompt/response metadata for POST /api/ai-local.",
    fields: {
      id: "string primary key",
      provider: "string",
      model: "string nullable",
      prompt: "string",
      response: "json nullable",
      status: "string",
      error: "string nullable",
      durationMs: "number nullable",
      createdAt: "datetime",
    },
  },

  provider: {
    table: "providers",
    purpose: "Store provider catalog records currently seeded through /api/providers/seed.",
    fields: {
      id: "string primary key",
      slug: "string unique",
      name: "string",
      serviceType: "string",
      rating: "number",
      serviceZips: "string array",
      pricing: "json",
      services: "string array",
      status: "string",
      createdAt: "datetime",
      updatedAt: "datetime",
    },
  },

  adminEvent: {
    table: "admin_events",
    purpose: "Store admin changes such as persistence toggle changes.",
    fields: {
      id: "string primary key",
      action: "string",
      requestBody: "json nullable",
      result: "json nullable",
      ip: "string nullable",
      userAgent: "string nullable",
      createdAt: "datetime",
    },
  },
};
